name: Job Scraping Cron Job

on:
  schedule:
    - cron: '0 12 * * *'  # Every day at 12:00 UTC
  workflow_dispatch:

jobs:
  scrape-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the Next.js app
        run: npm run build

      - name: Run job scraping
        run: |
          nohup npm run start > server.log 2>&1 &
          SERVER_PID=$!

          echo "Started server with PID $SERVER_PID"
          sleep 10

          if ps -p $SERVER_PID > /dev/null; then
            echo "Server is up, running scraping script..."
            node .github/scripts/triggerJobScraping.js

            kill $SERVER_PID
            echo "Killed server with PID $SERVER_PID"
          else
            echo "Server failed to start or already exited. Check server.log for details."
            cat server.log
            exit 1
          fi
