name: Trigger Job Scraping Cron

on:
  schedule:
    - cron: '0 5 * * *'  # Run at 5:00 AM UTC every day

jobs:
  trigger-job-scraping:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel API endpoint for Job Scraping
        run: |
          curl -X GET https://alertly-two.vercel.app/api/cron/job-scraping
